In [10]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [6]:
iris=pd.read_csv("C:\\Users\\91965\\Desktop\\tp-imp\\summer-AI\\datasets\\Iris.csv")

In [7]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
iris.shape

(150, 6)

In [9]:
iris.Species.value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [11]:
encode=LabelEncoder()

In [12]:
Species_encode=encode.fit(iris.Species)

In [13]:
print(Species_encode)

LabelEncoder()


In [17]:
Species_encode=encode.transform(iris.Species)

In [18]:
print(Species_encode)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [19]:
iris.head(50)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [20]:
iris.append(Species_encode)

C:\Users\91965\AppData\Local\Temp\ipykernel_5452\1424519309.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  iris.append(Species_encode)


TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid

In [22]:
data_set=pd.DataFrame(Species_encode)

In [32]:
data_set.head(20)

0
0   0
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   0
10  0
11  0
12  0
13  0
14  0
15  0
16  0
17  0
18  0
19  0

In [36]:
iris['output']=Species_encode

In [37]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.0            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
3   4            4.6           3.1            1.5           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   

   output  
0       0  
1       0  
2       0  
3       0  
4       0

In [40]:
iris=iris.drop(['Species'],axis=1)

In [41]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  output
0   1            5.1           3.5            1.4           0.2       0
1   2            4.9           3.0            1.4           0.2       0
2   3            4.7           3.2            1.3           0.2       0
3   4            4.6           3.1            1.5           0.2       0
4   5            5.0           3.6            1.4           0.2       0

In [42]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
output           0
dtype: int64

In [74]:
#  0 ==> Iris-setosa
#  1 ==> Iris-versicolor
#  2 ==> Iris-virginica
input_data=iris.drop(['output',"Id"],axis=1)
output=iris['output']
print(input_data)
print(output)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]
0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: output, Length: 150, dtype: int32


In [75]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
count  150.000000     150.000000    150.000000     150.000000    150.000000   
mean    75.500000       5.843333      3.054000       3.758667      1.198667   
std     43.445368       0.828066      0.433594       1.764420      0.763161   
min      1.000000       4.300000      2.000000       1.000000      0.100000   
25%     38.250000       5.100000      2.800000       1.600000      0.300000   
50%     75.500000       5.800000      3.000000       4.350000      1.300000   
75%    112.750000       6.400000      3.300000       5.100000      1.800000   
max    150.000000       7.900000      4.400000       6.900000      2.500000   

           output  
count  150.000000  
mean     1.000000  
std      0.819232  
min      0.000000  
25%      0.000000  
50%      1.000000  
75%      2.000000  
max      2.000000

In [76]:
scaler=StandardScaler()

In [77]:
input_std=scaler.fit_transform(input_data)

In [78]:
print(input_std)

[[-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00 -1.24957601e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.38535265e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00]
 [-5.37177559e-01  1.95766909e+00 -1.17067529e+00 -1.05003079e+00]
 [-1.50652052e+00  8.00654259e-01 -1.34127240e+00 -1.18150376e+00]
 [-1.02184904e+00  8.00654259e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.74885626e+00 -3.56360566e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00]
 [-5.37177559e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00]
 [-1.26418478e+00  8.00654259e-01 -1.22754100e+00 -1.31297673e+00]
 [-1.26418478e+00 -1.24957601e-01 -1.34127240e+00 -1.44444970e+00]
 [-1.87002413e+00 -1.24957601e-01 -1.51186952e+00 -1.44444970e+00]
 [-5.25060772e-02  2.18907205e+00 -1.45500381e+00 -1.31297673e

In [79]:
input_std.std()

1.0

In [80]:
output.std()

0.8192319205190405

In [81]:
# stratify is user for split labels in in equal manner 
# first input varibules second output varibules
train_in,test_in,train_out,test_out=train_test_split(input_std,output,test_size=0.2,stratify=output)

In [82]:
print(train_in.shape,train_out.shape,test_in.shape,test_out.shape)

(120, 4) (120,) (30, 4) (30,)


In [83]:
model_classifier=svm.SVC()

In [84]:
model_classifier.fit(train_in,train_out)

SVC()

In [85]:
predict=model_classifier.predict(train_in)
score=accuracy_score(predict,train_out)
print(score)

0.9666666666666667


In [86]:
test_predict=model_classifier.predict(test_in)
score_test=accuracy_score(test_predict,test_out)
print(score_test)

1.0


In [114]:
#testing the model iris-setosa
# without std prediction
specie0=np.array([4.9,3.0,1.4,0.2])
specie0=specie0.reshape(1,-1)
specie0=scaler.transform(specie0)
specie0_prediction=model_classifier.predict(specie0)
specie0_score=accuracy_score(specie0_prediction,np.array([0]))
print(specie0_score)
if specie0_prediction==0:
    print("Specie of Iris-setosa")
elif specie0_prediction==1:
    print("Specie of Iris-versicolor")
else:
    print("Specie of Iris-virginica")

1.0
Specie of Iris-setosa


In [109]:
# testing model iris-versicolor
# with std prediction
specie1=np.array([5.0,2.0,3.5,1.0])
specie1=specie1.reshape(1,-1)
#once use fit method then next dont use if you use then you get all zeroes
specie1=scaler.transform(specie1)
print(specie1)
specie1_prediction=model_classifier.predict(specie1)
if specie1_prediction==0:
     print("Specie of Iris-setosa")
elif specie1_prediction==1:
    print("Specie of Iris-versicolor")
else:
    print("Specie of Iris-virginica")
print("accuracy score is:",accuracy_score(specie1_prediction,np.array([1])))

[[0. 0. 0. 0.]]
Specie of Iris-versicolor
accuracy score is: 1.0


In [106]:
# testing model iris-virginica
# without std prediction
specie2=np.array([6.9,3.1,5.4,2.1])
specie2=specie2.reshape(1,-1)
specie2_prediction=model_classifier.predict(specie2)
specie2_score=accuracy_score(specie2_prediction,np.array([2]))
print(specie2_score)
print(specie2_prediction)
if specie2_prediction==0:
    print("Specie of Iris-setosa")
elif specie2_prediction==1:
    print("Specie of Iris-versicolor")
else:
    print("Specie of Iris-virginica")
# fail

0.0
[0]
Specie of Iris-setosa


In [105]:
# same prediction with std prediction
specie2=np.array([6.9,3.1,5.4,2.1])
specie2=specie2.reshape(1,-1)
specie2=scaler.transform(specie2)
specie2_prediction=model_classifier.predict(specie2)
specie2_score=accuracy_score(specie2_prediction,np.array([2]))
print(specie2_score)
print(specie2_prediction)
print(specie2)
if specie2_prediction==0:
    print("Specie of Iris-setosa")
elif specie2_prediction==1:
    print("Specie of Iris-versicolor")
else:
    print("Specie of Iris-virginica")

1.0
[2]
[[2.  0.1 4.  1.9]]
Specie of Iris-virginica
